email_domain: localhost
email_address: 
email_port: 25
email_user_name: 
email_password: 
email_authentication: :login
email_sender_address: tiny_vault@example.com
host: "tiny-vault"
language: en

exception_recipients: tiny_vault@example.de
exception_sender_address: '"Application Error" <app.error@example.com>'